### ISSUE TITLE
Make repository as template

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui_template#31]
I'm not sure if this is already done but would be nice to set the repo as a "template" https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

**Comment by 12rambau** [comment]
So nope that's not the case but what we have (already ready to flight) is the `module_factory` command in sepal_ui lib. It does pretty much the same + some initialization on your local machine (pre-commit hooks, create the venv, fill all the placeholders, and set-up a release branch). I've documented [here](https://sepal-ui.readthedocs.io/en/latest/tutorials/create-module.html#initialize-the-module).

we used it 2 days ago with @t-elisee. (https://github.com/t-elisee/ofgt_kmean).

Happy to have a look on what's possible to do directly from github

**Comment by 12rambau** [comment]
The repository is now a template and can be used as such. Be aware that only the master branch should be used and that all the placeholdres/readme/about section will not be adapted (links in the ui.ipynb as well).

I started a documentation section here: https://github.com/12rambau/sepal_ui/commit/bc5640b3b85247478dc9bf1b857377c09eb02adf

I'll close this issue for now, if you see any typo or want to improve the section help yourself !
